# -- Site Configuration --
baseURL = "https://zhenda-hub.github.io/"
defaultContentLanguage = "en"
theme = "blowfish"
enableRobotsTXT = true
pagination.pagerSize = 6
summaryLength = 0
hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "xcode"
    tabWidth = 2

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
