[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Series"
  pageRef = "/series/"
  weight = 20

[[main]]
  name = "Stats"
  pageRef = "/posts/blog-stats/"
  weight = 25

[[main]]
  name = "RSS"
  url = "/index.xml"
  weight = 26

[[main]]
  name = "Github"
  url = "https://github.com/zhenda-hub/"
  weight = 40

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 50

[[main]]
  name = "Links"
  pageRef = "/link/"
  weight = 60
