# -- Theme Options --
colorScheme = "blowfish"
# autumn
# avocado
# bloody
# blowfish
# congo
# fire
# forest
# github
# marvel
# neon
# noir
# one-light
# princess
# slate
# terminal
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
keywords = ["blog", "developer", "personal"]

[header]
  layout = "fixed"

[homepage]
  layout = "page"
  showRecent = true
  showRecentItems = 9
  cardView = true
  showMoreLink = true

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showWordCount = true
  showHeadingAnchors = true
  showTaxonomies = true
  showTableOfContents = true
  showBreadcrumbs = true
  showComments = true

[list]
  groupByYear = true
  cardView = true
  showSummary = true
